# Generated by Django 3.0.8 on 2020-07-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicboard', '0002_musicpost_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicpost',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
